[Options]
Dlls=GCACAD3.DLL : AC2GTYP.DLL
Enable Logging=0
Enable DebugLogging=0
Symbol Template File=
Memory Needed Per Native Element = 100000
Memory Needed Per Foreign Element = 10000

;
; Possible values for units are: 59=m, 61=mm, 62=cm, 63=km, 64=in, 65=ft, 66=yd, 67=mil 
;
Read Default Units=59

[Read Default View]
Type = Transformation Matrix
Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 

[Write Default View]
; Possible "Type" settings: "Standard", "Orthographic", "Transformation Matrix"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "NW Isometric", "NE Isometric", "SW Isometric", "SE Isometric"
; Possible "Transformation" sett. (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" sett. (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
Type = Transformation Matrix
Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 

[Entity Map]
;
; ACAD  to Gtype 3d entity map
;
ADLine = GLine : 0
ADCircle = GEllipse : 0
ADPolyline = 0 : GC_ADPolylineToGType
ADArc = GArc : 0
ADTrace = GLineString : 0
ADPoint = GPoint : 0
ADFace3d = GLineString : 0
ADSolid = GLineString : 0
ADInsert = 0 : GC_ADInsertToGType
ADMline = GLineString : 0
ADSpline = GBspCurve : 0
;ADSolid3d = GSatSolidString : 0
;ADSolid3d = GSatSolidStream : 0
ADSolid3d = GTypes : 0
;ADText = GTextBox : 0
;ADDimension = GDim : 0
;;;;;
;
; Release 13 entities added here.
;
ADEllipse = GEllipse : 0
ADSpline =  GBspCurve : 0
;;ADRegion =  : 0
;;ADSolid3d = : 0
;;ADRay =  : 0
;;ADXline = : 0
;ADMtext = GTextBox : 0
ADLeader = GLeader : 0
;;ADTolerance = : 0
;;ADMline =  : 0

;
; Gtype 3d to Acad entity map
;
GLine = ADLine : 0
GDimension = 0 : GC_GDimToADDimension
GDimStyle = ADDimStyle : 0 
;GLeader  = ADLeader :0
GEllipse = ADCircle : 0
GArc = ADArc : 0
GLineString = ADPolyline : 0
;GBspCurve = ADPolyline : 0
GPoint = ADPoint : 0
GSymbolDefinition = ADBlock : 0
GSymbolInstance = ADInsert : 0

[Option Forms]
Dll = ACADOPT.DLL
Import Entry Point = DisplayAutoCADImportForm
Export Entry Point = DisplayAutoCADExportForm

[Read Linestyles]
CONTINUOUS=9
DASHED=10
DASHED2=10
DASHEDX2=10
DASHEDX10=10
DOT=11
DOT2=11
DOTX2=11
DOTX10=11
DASHDOT=12
DASHDOT2=12
DASHDOTX2=12
DASHDOTX10=12
DIVIDE=13
DIVIDE2=13
DIVIDEX2=13
DIVIDEX10=13
BORDER=21
BORDER2=12
BORDERX2=21
HIDDEN=10
HIDDEN2=10
HIDDENX2=10
CENTER=18
CENTER2=18
CENTERX2=18
PHANTOM=20
PHANTOM2=20
PHANTOMX2=20

[Write Linestyles]
9=CONTINUOUS
10=DASHED2
11=DOT2
12=DASHDOT2
13=DIVIDE2
18=CENTER2
19=CENTER
20=PHANTOM2
21=BORDER2
23=CONTINUOUS

[Read Text Fonts]
txt.shx = Arial
romans.shx = Arial
romand.shx = Arial
gothice.shx = Algerian
sasb____.pfb = Arial Rounded MT
romant.shx = Bookman Old Style
italicc.shx = Bookman Old Style
bragga.ttf = Braggadocio
britanic.ttf = Britannic Bold
scripts.shx = Brush Script MT
italict.shx = Colonna MT
par_____.pfb = Courier New
desdemon.ttf = Desdemona
te______.pfb = Footlight MT Light
romanc.shx = Footlight MT Light
sasbo___.pfb = Footlight MT Light
teb_____.pfb = Impact
tel_____.pfb = Kino MT
monotxt.shx = Lucida Console
scriptc.shx = Matura MT Script
rom_____.pfb = Matura MT Script
playbill.ttf = Playbill
cibt____.ttf = Times New Roman
suf_____.ttf = Wide Latin

[Write Text Fonts]
MS Linedraw = txt.shx
Arial = romans.shx
Algerian = gothice.shx
Arial Rounded MT = sasb____.pfb
Bookman Old Style = romant.shx
Braggadocio = bragga.ttf
Britannic Bold = britanic.ttf
Brush Script MT = scripts.shx
Colonna MT = italict.shx
Courier New = par_____.pfb
Desdemona = desdemon.ttf
Footlight MT Light = te______.pfb
Impact = teb_____.pfb
Kino MT = tel_____.pfb
Lucida Console = monotxt.shx
Matura MT Script = scriptc.shx
Playbill = playbill.ttf
Times New Roman = cibt____.ttf
Wide Latin = suf_____.ttf

