[Options]
Enable Logging=1

[Read Default View]
; Possible "Type" settings: "Standard", "Orthographic", "Transformation Matrix", "Active"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "Isometric", "Right Isometric"
; Possible "Active View" settings (only if Type = Active): 1 - 8 to select that view orientation
; Possible "Transformation" sett. (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" sett. (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
; Type = Active
; Active View = 1
Type = Standard
Name = Top
Transformation = 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 
Reference Point = 0.0 0.0 0.0
Normal = 1.0 -1.0 1.0
Projection Vector = -1.0 0.0 0.0
; Type = Transformation Matrix
; Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 
