[Options]
Enable Logging=1

[Read Default View]
; Possible "Type" settings: "Standard", "Orthographic", "Transformation Matrix"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "Isometric", "Right Isometric"
; Possible "Transformation" sett. (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" sett. (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
Type = Transformation Matrix
Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 
