[Options]
Seed File=seedmet.ems
Enable Logging=1
; Possible values for units are: 59=m, 61=mm, 62=cm, 63=km, 64=in, 65=ft, 66=yd, 67=mil 
Read Default Units = 59
Template File = NORMAL.PAR
Batch Mode =0
SE_PS Output Files Option =  0
Original File Name = NULL
Output Directory Path = NULL
Read Part Name Prefix=
Read Part File Path=
Inplace translation=0
Healing and Sewing=0
[Option Forms]
Dll = EMSOPT.DLL
Export Entry Point = DisplayEMSExportForm
Import Entry Point = DisplayEMSImportForm
