set PATH=%PATH%
set IT_PRODUCT_DIR=%IT_PRODUCT_DIR%
set IT_CONFIG_DOMAINS_DIR=%IT_CONFIG_DOMAINS_DIR%
set IT_LICENSE_FILE=%IT_LICENSE_FILE%
set IT_DOMAIN_NAME=%IT_DOMAIN_NAME%
set JAVA_HOME=%JAVA_HOME%

itadmin ns list %1 >> %2