[Options]
Dlls=GCMDS.dll
Seed File=
BatchMode=0
;group=0 or intelligent=1
DimensionTransMode = 0
Enable Logging=1
LogFilePath =   
Override Colors = 1
Layers on off based on =
Symbology overrides  based on =
All Bold Text = 1
Possible values for units are: 59=m, 61=mm, 62=cm, 63=km, 64=in, 65=ft, 66=yd, 67=mil 
Read Default Units = 64
MS Resource Files =
Read Reference Paths=
Template File= NORMAL.DFT
Read Reference Options=Translate
Read Cell Options= Rigid groups
Write Version=5.0
Write Linestyle Resource Files=
Write Font Resource Files= 
Write Linked Objects=Ignore
Write Embedded Objects=Ignore
Sub Units Per Master Units = 10
Pos Units Per Sub Units = 1000
Symbol Template File= NORMAL.DFT
Memory Needed Per Native Element = 100000
Memory Needed Per Foreign Element = 10000

[Read Default View]
; Possible "Type" settings: "Standard", "Orthographic", "Transformation Matrix"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "Isometric", "Right Isometric"
; Possible "Transformation" sett. (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" sett. (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
Type = Standard
Name = Front
Transformation = 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 
Reference Point = 0.0 0.0 0.0
Normal = 1.0 -1.0 1.0
; Projection Vector = -1.0 0.0 0.0


[Option Forms]
Dll = MDSOPT.dll
Import Entry Point = MDSImptOptSheetOpen


[Read Text Fonts]
default=Arial
23=Courier New
30=arial
31=arial
15=arial
16=arial
17=arial
18=arial
2=impact
42=lucida console
0=arial
7=times new roman


[Read Widths]
0=.025
1=.035
2=.05
3=.0625
4=.07
5=.0875
6=0.1
7=.1125
8=.125
9=.14
10=.15
11=.1625
12=.175
13=.1875
14=.2
15=.2125
16=.225
17=.2375
18=.25
19=.2625
20=.275
21=.2875
22=.3
23=.3125
24=.325
25=.3375
26=.35
27=.3625
28=.375
29=.3875
30=.4
31=.4125

