[Options]
Dlls=GCPR2D.DLL
Enable Logging=0 
Enable DebugLogging=0
; =0	disabled
; =1	Processed type Npf_xxx to Gtype_yyy entity
; =2	NPF items encountered
; =4	NPF item data
; =8	NPF file dump
; combining allowed (15 = 1 && 2 && 4 && 8)
; Possible values for units are: 59=m, 61=mm, 62=cm, 63=km, 64=in, 65=ft, 66=yd, 67=mil
; -> z:\utils\include\uomrc.h 
Read Default Units = 61
Override Colors=0
Override Linetype Colors=0
Translate Scaled Layers=0
Template File=
;Template File=W:\MW\TEMPLATE\SPECIAL\Normmet.dft

[Option Forms]
Dll = NPFOPT.DLL
Import Entry Point = NpfImportOptionSheetOpen

[Read Default View]
Type = Standard
Name = Top
Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 
Reference Point = 0.0 0.0 0.0
Normal = 1.0 0.0 0.0
; Projection Vector = 1.0 1.0 1.0

[Entity Map]
;
; PROREN to Gtype 2D entity map
;
NpfGroupEnd             =GGroup         :0
NpfHatchDefEnd          =GGroup         :0
NpfHatchLine            =GLine2d        :0
NpfGeoLine              =GLine2d        :0
NpfGeoArc               =GArc2d         :0
NpfDimEnd               =GGroup         :0
NpfDimLinearEnd         =GDimension     :0
NpfDimRadialEnd         =GDimension     :0
NpfDimAngularEnd        =GDimension     :0
;NpfDimCoordEnd          =GDimension     :0
NpfDimCoordEnd          =0              :PrNpfDimCoordEnd
NpfDimHelpLineEnd       =GLine2d        :0
NpfDimLine              =GLine2d        :0
NpfDimArc               =GArc2d         :0
NpfDimTextEnd           =GTextBox       :0
NpfSymbolEnd            =GGroup         :0

[Read Linestyles]
[Read Text Fonts]
[Read Widths]

[Read Colors]
0=2626580
1=16777215
2=255
3=65280
4=10855680
5=6601175
6=48895
7=65535
8=30975
9=16744703
10=16776980
11=16711825
12=16711680
13=2977445
14=6592100
15=9568145

[Read Linetype Colors]
Linie dick=12
Linie duenn=3
Mittellinie=5
Freihandlinie=10
unsichtbar=12
Schraffur=13
Strichlinie=2
Strichpunktlinie dick=7
Strichpunktlinie duenn=5
Strichzweipunktlinie=14
Masslinie=4
Masshilfslinie=5
Symbol=4
Unbekannt=14
