;
; Entity Map from PROE to ...
;
[Option Forms]
Dll = PROEOPT.DLL
Import Entry Point = ProEImptOptSheetOpen
[Options]
RecognizeFeatures=0
Import Multiple Bodies As Single Part file=On
Import DoNotSave=On
