[Options]
Enable Logging=0
; Possible values for units are: 59=m, 61=mm, 62=cm, 63=km, 64=in, 65=ft, 66=yd, 67=mil 
Read Default Units = 59
Template File=
Read Part Template File=
Read Part Name Prefix=
Read Part File Path=
Major Version = 2
Minor Version = 0
Memory Needed Per Native Element = 100000
Memory Needed Per Foreign Element = 10000
MajorVersion=2
MinorVersion=0
Write Default Units=59

[Option Forms]
Dll = SATOPT.DLL
Import Entry Point = SatImptOptDialogOpen
Export Entry Point = SatExptOptDialogOpen
