;
; Entity Map from CATIA to ...
;
[Option Forms]
Dll = CatiaV5OPT.DLL
Import Entry Point = CatiaV5ImptOptSheetOpen
Export Entry Point = CatiaV5ExptOptSheetOpen
[Import Options]
Import Drive=C:
Import Path=
Import Feature Recognition=Off
Import Healing And Sewing=Off
Import Stitch Surfaces=On
Import Multiple Bodies As Single Part file=On
Import DoNotSave=On
Import Boolean Solids=On
Import Imprint Curves=On
Import Check bodies=Off
Import Make Base Feature=On
Import Enable Default Output Path=On
Import Output Path=
Import Simplify Geometry=Off
[Export Options]
Export Drive=C:
Export Path=
Export Construction Solids=Off
Export Construction Sheets=Off
Export Construction Wires=Off
Export Displayed Parts=Off
[Options]
Enable Logging=Off
Attribute Transfer=On
