;
; Entity Map from IGES to ...
;
[Option Forms]
Dll = IgesWizard.DLL
Import Entry Point = IgesWizardImportOptionSheetOpen
Export Entry Point = IgesWizardExportOptionSheetOpen

;
[Foreign To Neutral Translation Entity Map]
IGES_POINT=GPoint2d : 0
IGES_CONNECT_POINT=GPoint2d : 0
IGES_LINE=GLine2d : 0
IGES_COPIOUS_DATA=0 : GC_ConvertCopiousData
IGES_LINESTR=GLineString2d : 0
IGES_ARC=GArc2d : 0
IGES_CONIC=GBspCurve2d:0
IGES_BSP_CURVE=GBspCurve2d : 0
IGES_PARAMETRIC_CURVE=GBspCurve2d : 0
IGES_COMPOSITE_CURVE=GGroup : 0
IGES_WITNESS_LINE=GGroup : 0
IGES_CENTER_LINE=GGroup : 0
IGES_SECTION=GGroup : 0
IGES_SECTIONED_AREA=GGroup: 0
IGES_POINT_ARRAY=GGroup : 0
IGES_OFFSET_CURVE=GTypedCurve2d : 0
IGES_GENERAL_NOTE=GTextBox : 0
IGES_LEADER=GLeader2d : 0
IGES_GENERAL_LABEL=GGroup : 0
IGES_FLASH=GGroup : 0
IGES_LINEAR_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_ANGULAR_DIMENSION=GGroup: 0                                                                                                                                                                                             
IGES_RADIUS_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_DIAMETER_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_ORDINATE_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_POINT_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_CURVE_DIMENSION=0:GC_IGES_DIMENSIONToGGroup
;IGES_SUBFIGURE_INST=0:GC_IGES_SUBFIGToGSymInstance
;IGES_REC_SUBFIGURE_INST=0:GC_IGES_RECTANGLE_ARRAYToGGroup
;IGES_CIR_SUBFIGURE_INST=0:GC_IGES_CIRCLE_ARRAYToGGroup
;IGES_NET_SUBFIGURE_INST=0:GC_IGES_SUBFIGToGSymInstance
IGES_SUBFIGURE_INST=GGroup : 0
IGES_REC_SUBFIGURE_INST=GGroup : 0
IGES_CIR_SUBFIGURE_INST=GGroup : 0
IGES_ASSOCIATIVITY_INST=GGroup : 0
IGES_GENERAL_SYMBOL=GGroup : 0
IGES_FLAG_NOTE=GGroup : 0
IGES_EXTERNAL_REFERENCE= 0:GC_IGES_REFFILEToGReference

;
; Entity Map from Neutral format (GType2d) to IGES used by SE-Draft
;
[Neutral to Foreign Translation Entity Map]
GLine2d=IGES_LINE : 0
GBspCurve2d=IGES_BSP_CURVE : 0
GPoint2d=IGES_POINT : 0
GArc2d=IGES_ARC : 0
GEllipse2d=IGES_ARC : 0
GLineString2d=IGES_COPIOUS_DATA : 0
GRectangle2d=IGES_COPIOUS_DATA : 0
GGroup=IGES_ASSOCIATIVITY_INST : 0
GLeader2d=IGES_LEADER : 0
GComplexString2d=IGES_COMPOSITE_CURVE : 0
GText = 0 : GC_GTextBoxToIGES_GENERAL_NOTE


;
; Entity Map from Application format to Neutral format (GType2d) used by SE-Draft
;
[Application to Neutral Entity Map]
;
; Entity Map from IGES to Neutral format (GType2d) used by OLE Data Server
;
[Foreign to Neutral Server Entity Map]
IGES_POINT=GPoint2d : 0
IGES_CONNECT_POINT=GPoint2d : 0
IGES_LINE=GLine2d : 0
IGES_COPIOUS_DATA=0 : GC_ConvertCopiousData
IGES_LINESTR=GLineString2d : 0
IGES_ARC=GArc2d : 0
IGES_CONIC=GBspCurve2d:0
IGES_BSP_CURVE=GBspCurve2d : 0
IGES_PARAMETRIC_CURVE=GBspCurve2d : 0
IGES_COMPOSITE_CURVE=GGroup : 0
IGES_WITNESS_LINE=GGroup : 0
IGES_CENTER_LINE=GGroup : 0
IGES_SECTION=GGroup : 0
IGES_SECTIONED_AREA=GGroup: 0
IGES_POINT_ARRAY=GGroup : 0
IGES_OFFSET_CURVE=GTypedCurve2d : 0
IGES_GENERAL_NOTE=GTextBox : 0
IGES_LEADER=GLeader2d : 0
IGES_GENERAL_LABEL=GGroup : 0
IGES_FLASH=GGroup : 0
IGES_LINEAR_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_ANGULAR_DIMENSION=GGroup: 0                                                                                                                                                                                             
IGES_RADIUS_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_DIAMETER_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_ORDINATE_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_POINT_DIMENSION=0: GC_IGES_DIMENSIONToGGroup
IGES_CURVE_DIMENSION=0:GC_IGES_DIMENSIONToGGroup
;IGES_SUBFIGURE_INST=0:GC_IGES_SUBFIGToGSymInstance
;IGES_REC_SUBFIGURE_INST=0:GC_IGES_RECTANGLE_ARRAYToGGroup
;IGES_CIR_SUBFIGURE_INST=0:GC_IGES_CIRCLE_ARRAYToGGroup
;IGES_NET_SUBFIGURE_INST=0:GC_IGES_SUBFIGToGSymInstance
IGES_SUBFIGURE_INST=GGroup : 0
IGES_REC_SUBFIGURE_INST=GGroup : 0
IGES_CIR_SUBFIGURE_INST=GGroup : 0
IGES_ASSOCIATIVITY_INST=GGroup : 0
IGES_GENERAL_SYMBOL=GGroup : 0
IGES_FLAG_NOTE=GGroup : 0
IGES_EXTERNAL_REFERENCE= 0:GC_IGES_REFFILEToGReference


[Read Linestyles]
0=9
1=9
2=10
3=20
4=18
5=11

[Write Linestyles]
9=1
10=2
20=3
18=4
11=5

 
[Read Hatchstyles]
1=ANSI31(Iron)
2=ANSI32(Steel)
4=ANSI34(Plastic)
5=Normal Dash
9=ANSI33(Brass)
10=Insulation Material
13=ANSI32(Steel)
14=ANSI34(Plastic)
16=ANSI37(Lead)
17=ANSI38(Aluminum)
18=Normal Grid
70=Flexible Material

[Write Hatchstyles]
ANSI31(Iron)=1
ANSI32(Steel)=2
ANSI33(Brass)=9
ANSI34(Plastic)=4
ANSI37(Lead)=16
ANSI38(Aluminum)=17
Flexible Material=70
Insulation Material=10
Normal Dash=5
Normal Grid=8
 
[Options]
Dlls=GCIGES.DLL
Enable Logging=0
Enable DebugLogging=0
Terminators=1
; Possible values for units are: 59=m, 61=mm, 62=cm, 63=km, 64=in, 65=ft, 66=yd, 67=mil 
Read Default Units = 61
Read Cell Options= Shared embeds
Write Version=5.0
Symbol Template File=
Memory Needed Per Native Element = 100000
Memory Needed Per Foreign Element = 10000
Processing Batch Translation =    0
MFC Application = 0
Stroke Dimension = 1
Delete Symbol Definitions = 1
Background Color=255,0,255
Map Colors=0

;The following option determines the max. nesting depth for display/locate of reference
;files.  Valid values are 0 (ignore all nested references) and -1 (display ALL nested references)
Max. Nesting Depth = 0
Sub Units Per Master Units=0
Pos Units Per Sub Units=0
Write Linestyle Resource Files=
Write Font Resource Files=

[Read Default View]
; Possible "Type" settings: "Standard", "Active","Orthographic", "Transformation Matrix"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "Isometric", "Right Isometric"
; Possible "Active View" settings (only if Type = Active): 1 - 8.
; Possible "Transformation" settings (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" settings (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
Type = Standard
Name = Top
Transformation = 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0 0 
Reference Point = 0.0 0.0 0.0
Normal = 1.0 -1.0 1.0
; Projection Vector = -1.0 0.0 0.0

[Write Default View]
; Possible "Type" settings: "Standard", "Orthographic", "Transformation Matrix"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "Isometric", "Right Isometric"
; Possible "Transformation" sett. (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" sett. (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
Type = Standard
Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 
Reference Point = 0.0 1.0 0.0
Normal = 0.0 0.0 1.0

[Read Text Fonts]
1=Arial
2=Arial
3=Arial
6=Arial
9=Solid Edge ISO2 Symbols
12=Arial
13=Gothicl
14=Simplex
17=Arial
18=Arial
19=Arial
1001=IGES 1001
1002=IGES 1002
1003=IGES 1003

[Write Text Fonts]
Arial=1
Solid Edge ANSI=1
Solid Edge ANSI2 Symbols=9
Solid Edge ANSI3 Symbols=1003
Solid Edge ISO=1
Solid Edge ISO1 Symbols=1001
Solid Edge ISO2 Symbols=9
Solid Edge ISO3 Symbols=1003

[Read Widths]
[Import Options 3D]
Import Drive=C:
Import Path=
Import Free Curves=On
Import Free Surfaces=On
Import Trimmed Surfaces=On
Import MSBO Entities=On
Import Sew Free Surfaces=On
Import Blank Entities=On
Import Maximum Sewing Tolerance=0.001000000000000
Import Minimum Sewing Tolerance=0.000001000000000
Import Sewing Tolerance Incriment=10.000000
Import Flavor=None
Import Model Units=meters
Import Simplify Geometry=On
Import Recognize Features=Off
Import Bodies=Surfaces and Solids
Import Healing And Sewing=Off
Import DoNotSave=On
[Export Options 3D]
Export Drive=C:
Export Path=
Export Author=Author
Export Organization=Title
Export Originating System=Solid Edge
Export Receiving System=Unknown
Export Flavor=None
Export Body Type=Trimmed Surface
Export IGES Units=mm
Export Tube Centerlines=Off
Export Start Section=Comment
Export End Of Line Character Width=1
[3D Options]
Temporary Directory=
