;
; Entity Map from SAT to ...
;
[Option Forms]
Dll = SAT3OPT.DLL
Import Entry Point = Sat3DImptOptSheetOpen
Export Entry Point = Sat3DExptOptSheetOpen
[Import Options]
Import Drive=C:
Import Path=
Import Feature Recognition=Off
Import Healing And Sewing=Off
Import Units=Millimeters
Import DoNotSave=On
[Export Options]
Export Drive=C:
Export Path=
Export Constructions=Off
Export Version=13.0
[Options]
Enable Logging=Off
