[Options]
Dlls=GCACAD.DLL
Sheet Metal Configuration = 1
Enable Logging=0
;Enable DebugLogging=0
Read Default Units=64
Template File=
;Read Block Options=Shared embeds
;Read Block Options=Rigid groups
Write Version=14
;Write Linked Objects=Ignore
;Write Embedded Objects=Ignore
Seed File=
Write Polyline Width Threshold=10.0000000
;Symbol Template File=
Memory Needed Per Native Element = 100000
Memory Needed Per Foreign Element = 10000
Read Default Width=0.000010000
Processing Batch Translation = 0
MFC Application = 0
Process PaperSpace = 1
Stroke Pattern = 1
Use Pattern Name = 1
Style Resource Name =
AutoCAD Extended Data = ACADASE
Delete Symbol Definitions = 1
Export All Graphics to PaperSpace = 0
Process Non-Displayable Reference files = 1 
Process Multiple Orientation in Viewports = 0
Dissolve Symbol to Groups = 1
Application Text Type = 0
Bigfont Name =
Part Layers = 1
Break Dimensions = 0
Time Stamp = 15



;The following option determines the max. nesting depth for display/locate of reference
;files.  Valid values are 0 (ignore all nested references) and -1 (display ALL nested references)
Max. Nesting Depth = -1
Write Linestyle Resource Files=
Write Font Resource Files=

[Read Default View]
; Possible "Type" settings: "Standard", "Active", "Orthographic", "Transformation Matrix"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "NW Isometric", "NE Isometric", "SW Isometric", "SE Isometric"
; Possible "Active view" settings (only if Type = Active): none 
; Possible "Transformation" sett. (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" sett. (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
;Type = Standard
;Name = Top
;Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 
;Reference Point = 0.0 0.0 0.0
;Normal = 1.0 0.0 0.0
;Projection Vector = 1.0 1.0 1.0

[Write Default View]
; Possible "Type" settings: "Standard", "Orthographic", "Transformation Matrix"
; Possible "Name" settings (only if Type = Standard): "Top", "Bottom", "Front", "Back",
; "Right", "Left", "NW Isometric", "NE Isometric", "SW Isometric", "SE Isometric"
; Possible "Transformation" sett. (only if Type = Transformation Matrix): any 4x4 
; column major transformation matrix
; Possible "Reference Point" sett. (only if Type = "Orthographic"): Point on 
; Viewing Plane
; Possible "Normal" sett. (only if Type = "Orthographic"): completes the 
; definition of the plane passing through "Reference Point"
Type = Transformation Matrix
Transformation=1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 
Reference Point = 0.0 1.0 0.0
Normal = 0.0 0.0 1.0

;
; Entity Map from AutoCAD to Neutral format (GType2d) used by Solid Edge
;
[Foreign to Neutral Translation Entity Map]
;ADLine = GLine2d : 0
;ADCircle = GEllipse2d : 0
;ADPolyline = 0 : GC_ADPolylineToGType2d
;ADArc = GArc2d : 0
;ADTrace = GLine2d : 0
;ADPoint = GPoint2d : 0
;ADFace3d = GLine2d : 0
;ADSolid = GLineString2d : 0
;ADInsert = 0 : GC_ADInsertToGType2d
;ADInsert = GSymbolInstance : 0
;ADMline = GLineString2d : 0
;ADSpline = GBspCurve2d : 0
;ADDimension = GDim2d : 0
;ADText = GTextBox : 0
;ADAttrib = GTextBox : 0
;ADAttdef = GTextBox : 0
;ADPViewport = GReference : 0
;ADXline = GLine2d : 0
;ADRay = GLine2d : 0
;;;;;
;
; Release 13 entities added here.
;
;ADEllipse = GEllipse2d : 0
;ADSpline =  GBspCurve2d : 0
;;ADRegion =  : 0
;;ADSolid3d = : 0
;;ADRay =  : 0
;;ADXline = : 0
;ADMtext = GTextBox : 0
;ADLeader = GLeader2d : 0
;ADTolerance = GGroup2d: 0
;;ADMline =  : 0
;;;;;
;
; Release 14 entities added here.
;
;ADHatch = GBoundary2d : 0
;;;;;;

;
; Entity Map from Neutral format (GType2d) to AutoCAD used by Solid Edge
;
[Neutral to Foreign Translation Entity Map]
GLine2d = ADLine : 0
GDimension = 0 : GC_GDim2dToADDimension
GDimStyle2d = ADDimStyle : 0 
GLeader2d  = ADLeader : 0
GEllipse2d = ADCircle : 0
GArc2d = ADArc : 0
GLineString2d = ADPolyline : 0
GBspCurve2d = ADPolyline : 0
GPoint2d = ADPoint : 0
GRectangle2d = ADPolyline : 0
GGroup = ADEntity : 0
;GComplexString2d = ADEntity  : 0
GComplexString2d = ADPolyline  : 0
GText = ADText : 0
GSymbolDefinition2d = ADBlock : 0
GSymbolInstance2d = ADInsert : 0
GReference = ADXRef : 0

;
; Entity Map from Application format to Neutral format (GType2d) used by Solid Edge
;
[Application to Neutral Entity Map]

;
; Entity Map from AutoCAD to Neutral format (GType2d) used by OLE Data Server
;
[Foreign to Neutral Server Entity Map]
;ADLine = GLine2d : 0
;ADCircle = GEllipse2d : 0
;ADPolyline = 0 : GC_ADPolylineToGEntity2d
;ADArc = GArc2d : 0
;ADTrace = GLine2d : 0
;ADPoint = GPoint2d : 0
;ADFace3d = GLine2d : 0
;ADSolid = GLineString2d : 0
;ADInsert = 0 : GC_ADInsertToGType2d
;;ADInsert = GSymbolInstance : 0
;ADMline = GLineString2d : 0
;ADText = 0 : GC_ADTextToVWGTextBox
;ADSpline = GBspCurve2d : 0
;ADXline = GLine2d : 0
;ADRay = GLine2d : 0
;ADDimension = GDimGraph : 0
;ADAttrib = 0 : GC_ADAttribToVWGTextBox
;ADAttdef = 0 : GC_ADAttdefToVWGTextBox
;;;;;
;
; Release 13 entities added here.
;
;ADEllipse = GEllipse2d : 0
;ADSpline =  GBspCurve2d : 0
;;ADRegion =  : 0
;;ADSolid3d = : 0
;;ADRay =  : 0
;;ADXline = : 0
;ADMtext = 0 : GC_ADMtextToVWGTextBox
;ADLeader =  GGraphic : 0
;ADTolerance = GGroup2d : 0
;;ADMline =  : 0

[Option Forms]
Dll = ACADOPT.DLL
Import Entry Point = DisplayAutoCADImportForm
Export Entry Point = DisplayAutoCADExportForm

[Read Linestyles]
;CONTINUOUS=9
;DASHED=10
;DASHED2=10
;DASHEDX2=10
;DASHEDX10=10
;DOT=11
;DOT2=11
;DOTX2=11
;DOTX10=11
;DASHDOT=12
;DASHDOT2=12
;DASHDOTX2=12
;DASHDOTX10=12
;DIVIDE=13
;DIVIDE2=13
;DIVIDEX2=13
;DIVIDEX10=13
;BORDER=21
;BORDER2=12
;BORDERX2=21
;HIDDEN=10
;HIDDEN2=10
;HIDDENX2=10
;CENTER=18
;CENTER2=18
;CENTERX2=18
;PHANTOM=20
;PHANTOM2=20
;PHANTOMX2=20

;In the following sections of the .INI file, the numbers correspond
;to the following line styles in Solid Edge. DO NOT Add to, Remove from, or change
;the order of the lists. The Linestyle Names, Linestyle Colors, and Linestyle Weights
;may be changed.
;9 - Continuous
;10 - Dash
;11 - Dot
;12 - DashDot
;13 - DashDotDot
;18 - Chain
;19 - CenteredChain
;20 - DoubleChain
;21 - DashDashDot
;23 - EndGap

;The Following map is used to define the ACAD line type to create.
;The line type defines the dash sequences.
;The following line types can be defined. DO NOT CHANGE THE NAMES!
;Use only the names listed below in this section.
;The string names for each of the following types are defined in the
;"Write Linestyle Names" section of this .ini file.
;CONTINUOUS, DASHED, DASHED2, DASHEDX2, DASHEDX10, DOT, DOT2,
;DOTX2, DOTX10, DASHDOT, DASHDOT2, DASHDOTX2, DASHDOTX10, DIVIDE,
;DIVIDE2, DIVIDEX2, DIVIDEX10, BORDER, BORDER2, BORDERX2, CENTER,
;CENTER2, CENTERX2, HIDDEN, HIDDEN2, HIDDENX2, PHANTOM, PHANTOM2,
;PHANTOMX2
[Write Linestyles]
9=CONTINUOUS
10=HIDDEN2
11=DOT2
12=DASHDOT2
13=DIVIDE
18=CENTER2
19=CENTER
20=PHANTOM2
21=BORDER2
23=CONTINUOUS

;Use this section to define the string names for the line types.
;This does not define the type, only the string name for the type.
;To define the type, use the "Write Linestyles" section of this .ini
;file.
[Write Linestyle Names]
9=CONTINUOUS
10=HIDDEN2
11=DOT2
12=DASHDOT2
13=DIVIDE
18=CENTER2
19=CENTER
20=PHANTOM2
21=BORDER2
23=CONTINUOUS

; The following is the mapping fo the linetype to each feature
[Write Feature To Line Type]
0=9
1=18
2=18
3=9
4=9
5=9
6=9
7=9
8=9

; The following section is the colors to export for each feature
; The acceptable values and their mapping are:
;   1=Red
;   2=Yellow
;   3=Green
;   4=Cyan
;   5=Blue
;   6=Magenta
;   7=White/Black (inverse of background color)
[Write Feature To Color]
0=3
1=4
2=4
3=2
4=3
5=3
6=3
7=7
8=7

;The Following section defines the weights used by each of the line styles
;when translating Sheet Metal Flat Pattern to ACAD
[Write Linestyle Weights]
9=.007
10=.0035
11=.0035
12=.0035
13=.0035
18=.0035
19=.0035
20=.0035
21=.0035
23=.0035

;The Following section specifies the names of the layers to create 
;when translating Sheet Metal Flat Pattern to ACAD
[Write Layer Names]
0=Other
1=Down Centerlines
2=Up Centerlines
3=Down Features
4=Up Features
5=Outer Loop
6=Interior Loops
7=Complex Hole
8=Etch

;The Following section specifies if the layers are to be displayed
;on file open when translating Sheet Metal Flat Pattern to ACAD
[Write Layer Displays]
0=1
1=1
2=1
3=1
4=1
5=1
6=1
7=1
8=1

;The Following section specifies if the layer locks or locates are applied 
;to the AutoCAD layer when translating Sheet Metal Flat Pattern to ACAD.
[Write Layer Locates]
0=0
1=0
2=0
3=0
4=0
5=0
6=0
7=0
8=0

[Read Hatchstyles]
;ANGLE=Angle Steel
;ANSI31=ANSI31(Iron)
;ANSI32=ANSI32(Steel)
;ANSI33=ANSI33(Brass)
;ANSI34=ANSI34(Plastic)
;ANSI35=ANSI35(Fire Brick)
;ANSI36=ANSI36(Marble)
;ANSI37=ANSI37(Lead)
;ANSI38=ANSI38(Aluminum)
;CORK=Cork
;FLEX=Flexible Material
;TRANS=Heat Transfer
;HONEY=Honeycomb
;INSUL=Insulation Material
;ACAD_ISO02W100=ISO02W100
;ACAD_ISO03W100=ISO03W100
;ACAD_ISO04W100=ISO04W100
;ACAD_ISO05W100=ISO05W100
;ACAD_ISO06W100=ISO06W100
;ACAD_ISO07W100=ISO07W100
;ACAD_ISO08W100=ISO08W100
;ACAD_ISO09W100=ISO09W100
;ACAD_ISO10W100=ISO10W100
;ACAD_ISO11W100=ISO11W100
;ACAD_ISO12W100=ISO12W100
;ACAD_ISO13W100=ISO13W100
;ACAD_ISO14W100=ISO14W100
;ACAD_ISO15W100=ISO15W100
;LINE=Normal
;DASH=Normal Dash
;_U=Normal Grid
;NET3=Normal Mesh

[Write Hatchstyles]
;Angle Steel=ANGLE
;ANSI31(Iron)=ANSI31
;ANSI32(Steel)=ANSI32
;ANSI33(Brass)=ANSI33
;ANSI34(Plastic)=ANSI34
;ANSI35(Fire Brick)=ANSI35
;ANSI36(Marble)=ANSI36
;ANSI37(Lead)=ANSI37
;ANSI38(Aluminum)=ANSI38
;Cork=CORK
;Flexible Material=FLEX
;Heat Transfer=TRANS
;Honeycomb=HONEY
;Insulation Material=INSUL
;ISO02W100=ACAD_ISO02W100
;ISO03W100=ACAD_ISO03W100
;ISO04W100=ACAD_ISO04W100
;ISO05W100=ACAD_ISO05W100
;ISO06W100=ACAD_ISO06W100
;ISO07W100=ACAD_ISO07W100
;ISO08W100=ACAD_ISO08W100
;ISO09W100=ACAD_ISO09W100
;ISO10W100=ACAD_ISO10W100
;ISO11W100=ACAD_ISO11W100
;ISO12W100=ACAD_ISO12W100
;ISO13W100=ACAD_ISO13W100
;ISO14W100=ACAD_ISO14W100
;ISO15W100=ACAD_ISO15W100
;Normal=LINE
;Normal Dash=DASH
;Normal Grid=_U
;Normal Mesh=NET3

[Read Text Fonts]
;txt.shx=Arial
;romans.shx=Arial
;romand.shx=Arial
;gothice.shx=Algerian
;sasb____.pfb=Arial Rounded MT Bold
;romant.shx=Bookman Old Style
;italicc.shx=Bookman Old Style
;bragga.ttf=Braggadocio
;britanic.ttf=Britannic Bold
;scripts.shx=Brush Script MT
;italict.shx=Colonna MT
;par_____.pfb=Courier New
;desdemon.ttf=Desdemona
;te______.pfb=Footlight MT Light
;romanc.shx=Footlight MT Light
;sasbo___.pfb=Footlight MT Light
;teb_____.pfb=Impact
;tel_____.pfb=Kino MT
;monotxt.shx=Lucida Console
;scriptc.shx=Matura MT Script Capitals
;rom_____.pfb=Matura MT Script Capitals
;playbill.ttf=Playbill
;cibt____.ttf=Times New Roman
;suf_____.ttf=Wide Latin

[Write Text Fonts]
;MS Linedraw=txt.shx
;Arial=romans.shx
;Algerian=gothice.shx
;Arial Rounded MT Bold=sas_____.pfb
;Bookman Old Style=romant.shx
;Brush Script MT=scripts.shx
;Colonna MT=italict.shx
;Courier New=par_____.pfb
;Footlight MT Light=te______.pfb
;Impact=teb_____.pfb
;Kino MT=tel_____.pfb
;Lucida Console=monotxt.shx
;Matura MT Script Capitals=scripts.shx
;Times New Roman=suf_____.pfb
;Wide Latin=suf_____.pfb
;Solid Edge ANSI=igransi.ttf
;Solid Edge ANSI1 Symbols=igrmeca1.ttf
;Solid Edge ANSI2 Symbols=igrmeca2.ttf
;Solid Edge ISO1 Symbols=igrmeci1.ttf
;Solid Edge ISO2 Symbols=igrmeci2.ttf
;Solid Edge ISO=igriso.ttf

[Read Widths]

[Write Widths]
[Reference Face Data]
RefId=111

; The following is the export toggle.
[Write Export Feature]
0=1
1=1
2=1
3=1
4=1
5=1
6=1
7=0
8=0
