;
; Entity Map from STEP to ...
;
[Option Forms]
Dll = STP3OPT.DLL
Import Entry Point = Step3DImptOptSheetOpen
Export Entry Point = Step3DExptOptSheetOpen
[Import Options]
Import Drive=C:
Import Path=
Import Class2 Wireframe=On
Import Class3 Wireframe=On
Import Class4 Surface Models=On
Import Class5 Faceted Solids=On
Import Class6 Solids=On
Import Sew ClassII Surfaces=On
Import Simplify Geometry=On
Import Read Product ID Attribute=On
Import Feature Recognition=Off
Import Multiple Bodies As Single Part file=On
Import DoNotSave=On
[Export Options]
Export Drive=C:
Export Path=
Export Units=Millimeters
Export Solid Bodies As=Solid
Export Tube Centerlines=Off
Export Author=Unknown
Export Organization=Unknown
Export Program Name=Unknown
Export Time Stamp=Unknown
Export Description=Unknown
[Options]
Enable Logging=On
Healing And Sewing=Off
