[Languages]
;Format: Language.Codepage=subdir
English.1252=C
German.1252=Program\ResDLLs\0009\ResEAI
Italian.1252=Program\ResDLLs\0009\ResEAI
French.1252=Program\ResDLLs\0009\ResEAI
Japanese.932=Program\ResDLLs\0009\ResEAI
Korean.949=Program\ResDLLs\0009\ResEAI
Chinese.936=Program\ResDLLs\0009\ResEAI
Chinese.950=Program\ResDLLs\0009\ResEAI
Portuguese.1252=Program\ResDLLs\0009\ResEAI
Spanish.1252=Program\ResDLLs\0009\ResEAI
;
Catalan.1252=C
Danish.1252=C
Finnish.1252=C
Icelandic.1252=C
Dutch.1252=C
Norwegian.1252=C
Swedish.1252=C
Indonesian.1252=C
Basque.1252=C
Afrikaans.1252=C
Faroese.1252=C
Malay.1252=C
Swahili.1252=C
Galician.1252=C

