[Info]
Name=INTL
Version=1.00.000
DiskSpace=8000	;DiskSpace requirement in KB

[Startup]
CmdLine=
SuppressWrongOS=N
ScriptDriven=2
ScriptVer=11.50.0.42618
DotNetOptionalInstallIfSilent=N
OnUpgrade=0
RequireExactLangMatch=0404,0804
Product=Insight Connect V20
PackageName=Insight Connect V20.msi
EnableLangDlg=N
LogResults=N
DoMaintenance=N
ProductCode={3AC0F55F-D646-46B5-891A-3A94BBBF510C}
ProductVersion=20.00.0096
SuppressReboot=Y
PackageCode={6918735E-1B1F-4467-AD75-AC07C1016A0C}

[MsiVersion]
3.0.3790.2180=SupportOSMsi30

[SupportOSMsi11] ;Supported platforms for MSI 1.1
Win95=1
Win98=1
WinNT4SP3=1

[SupportOSMsi12] ;Supported platforms for MSI 1.2
Win95=1
Win98=1
WinME=1
WinNT4SP3=1

[SupportOS] ;Supported platforms for MSI 2.0
Win95=1
Win98=1
WinME=1
WinNT4SP6=1
Win2K=1

[SupportOSMsi30] ;Supported platforms for MSI 3.0
Win2KSP3=1
WinXP=1
Win2003Server=1

[Win95]
MajorVer=4
MinorVer=0
MinorVerMax=1
BuildNo=950
PlatformId=1

[Win98]
MajorVer=4
MinorVer=10
MinorVerMax=11
BuildNo=1998
PlatformId=1

[WinME]
MajorVer=4
MinorVer=90
MinorVerMax=91
BuildNo=3000
PlatformId=1

[WinNT4SP3]
MajorVer=4
MinorVer=0
MinorVerMax=1
BuildNo=1381
PlatformId=2
ServicePack=768

[WinNT4SP6]
MajorVer=4
MinorVer=0
MinorVerMax=1
BuildNo=1381
PlatformId=2
ServicePack=1536

[Win2K]
MajorVer=5
MinorVer=0
MinorVerMax=1
BuildNo=2195
PlatformId=2

[Win2KSP3]
MajorVer=5
MinorVer=0
MinorVerMax=1
BuildNo=2195
PlatformId=2
ServicePack=768

[WinXP]
MajorVer=5
MinorVer=1
MinorVerMax=2
BuildNo=2600
PlatformId=2

[Win2003Server]
MajorVer=5
MinorVer=2
MinorVerMax=3
BuildNo=2600
PlatformId=2




[Languages]
count=1
default=409
key0=409
[Insight Connect V20.msi]
Type=0
Location=Insight Connect V20.msi
[Setup.bmp]
Type=0
[instmsi30.exe]
Type=0
Location=instmsi30.exe
[ISScript.msi]
Type=0
Location=ISScript1150.Msi
[ISSetupPrerequisites]
PreReq0=Microsoft .NET Framework 2.0 for Windows XP x64 (64 bit).prq
PreReq1=Microsoft .NET Framework 2.0 for Windows XP (32 bit).prq
