[Option Forms]
Dll = TrnSupX.DLL
Export Entry Point = SEPVExportOptionForm
Import Entry point = JTImportForm

[Options]
Enable Logging = 0
Include Precise Geometry =1
JT Units=m
chordalOption=RELATIVE
structureOption=FULL_SHATTER
writeWhichFiles=ALL
pmiOption=NONE
partMonitor=false
compression=true
triStripOpt=true
seamSewing=true
seamSewingTol=0.001
brepPrecision=DOUBLE
autoNameSanitize=false
deleteUnusedParts=false
writeAsciiAssembly=false
autoLowLODgeneration=true
smartLODgeneration=false
Number of LODs=3
AdvacedCompressionOn=false
AdvacedCompressionLevel=0
XTBasedNewFormat=true
IncludeVisibleConstructions=true
IncludeSEProperties=true
ApplySimplifiedTopAsmOverride=false
ApplySimplifiedSubAsmOverride=false
ApplySimplifiedPartOverride=false
Export Inter-Part Copies as constructions=false
updateChangedPartsOnly=false
SEPartFileAsSingleJTFile=true
Export Visible Parts Only=false
Export PMI=false


[LOD 1]
Chordal=0.001
Angular=20
Length=0
FeatureSuppression=0
Simplify=1.0

[LOD 2]
Chordal=0.0035
Angular=0
Length=0
FeatureSuppression=0
Simplify=0.4

[LOD 3]
Chordal=0.01
Angular=0
Length=0
FeatureSuppression=0
Simplify=0.1

[Import Property map]
; This is the mapping table used to Map JT user attributes to SE file properties.
; Left hand side of equal sign indicates the parameter name found in Solid Edge
; Right hand side of the equal sign indicates the user attribute data found in the jt file.
; If jt attributes are not mapped in this table they are placed as custom properties in the SE file 
; Sample mapping for JT files created in IDEAS
;
;Document Number = I-DEAS Part Number
;Author = Creator 
;Project Name = I-DEAS Project 
;Density = CAD_Density
;Sample Mapping for JT files created in SE (loop test)
;
;SUMMARY TAB
;

Title = Title
Subject = Subject
Author = Author
Manager = Manager
Company = Company
Category = Category
Keywords = Keywords
Comments = Comments
;PROJECT TAB
Document Number = Document Number
Revision = Revision
Project Name = Project Name
Density = CAD_Density


