%system%
JID='%jid%'
OUT='%out%'
MEM=%mem%
MACH='%s.type%'
OPER='%s.os%'
OSV='%s.osv%'
MODEL='%s.model% (%s.hostname=\([^.]*\)%)'
NPROC='%s.nproc%'
CONFIG=%config%
%nproc:NPROC={}%
%sysfield%
%symbol%
SDIR='%sdir%/%j.base%.%j.unique%'
DBS='%dbs%'
SCR=%scr%
%smem:SMEM={}%
NEWDEL='%a.sss%'
%smaster:SMASTER={}%
%sdball:SDBALL={}%
%sscr:SSCR={}%
DEL='%del%'
AUTH='%auth%'
%authqueue:AUTHQUE={}%
%authinfo:AUTHINFO={}%
%gmconn:GMCONN='{}'%
%msgcat:MSGCAT='{}'%
%msgdest:MSGDEST='{}'%
%prog:PROG={}%
%j.news:NEWS='{}'%
%solution:SOL={}%
%version>=1.0:%%j.params%
