Rem  This is the EDS Corporation Product
Rem  Initialization file.
;

[Solver]
;
; This section contains general specifications for
; NASTRAN execution.
;
VERS=4.0

[Nastran]
;
; This section contains specifications expressly for NASTRAN.
;

